// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "post": {
                "description": "パラメータのtextを出力する",
                "tags": [
                    "index"
                ],
                "parameters": [
                    {
                        "description": "入力テキスト",
                        "name": "text",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/index.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出力メッセージ",
                        "schema": {
                            "$ref": "#/definitions/index.PostIndexResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "index.PostIndexResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "こんにちは！"
                }
            }
        },
        "index.RequestBody": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "type": "string",
                    "example": "こんにちは！"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "go_echo API",
	Description:      "Go言語（Golang）のフレームワーク「Echo」によるバックエンドAPIのサンプル",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
