basePath: /api/v1
definitions:
  index.PostIndexResponse:
    properties:
      message:
        example: こんにちは！
        type: string
    type: object
  index.RequestBody:
    properties:
      text:
        example: こんにちは！
        type: string
    required:
    - text
    type: object
host: localhost
info:
  contact: {}
  description: Go言語（Golang）のフレームワーク「Echo」によるバックエンドAPIのサンプル
  title: go_echo API
  version: "1.0"
paths:
  /hello:
    post:
      description: パラメータのtextを出力する
      parameters:
      - description: 入力テキスト
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/index.RequestBody'
      responses:
        "200":
          description: 出力メッセージ
          schema:
            $ref: '#/definitions/index.PostIndexResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - index
swagger: "2.0"
