services:
  api:
    container_name: go-echo-api
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    env_file:
      - ./.env
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    tty: true
    stdin_open: true
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    container_name: go-echo-db
    image: mysql:8.0.37
    env_file:
      - ./.env 
    ports:
      - 3306:3306
    volumes:
      - ./docker/local/db/init:/docker-entrypoint-initdb.d/
      - ./docker/local/db/conf:/etc/mysql/conf.d/
      - mysql-echo-db:/var/lib/mysql
volumes:
  mysql-echo-db:
    driver: local